-- liquibase formatted sql

-- changeset Caveri:1

create table avatar
(
    id         bigint NOT NULL generated by default as identity primary key,
    data       oid,
    file_path  varchar(255),
    file_size  bigint NOT NULL,
    media_type varchar(255),
    student_id bigint
);

