-- liquibase formatted sql

-- changeset Caveri:1

create table faculty
(
    id    bigint NOT NULL generated by default as identity primary key,
    color varchar(255),
    name  varchar(255)
);

-- changeset Caveri:2

ALTER TABLE faculty ADD CONSTRAINT name_unique UNIQUE (name);