-- liquibase formatted sql

-- changeset Caveri:1

create table student
(
    id         bigint NOT NULL generated by default as identity primary key,
    age        integer not null,
    name       varchar(255),
    faculty_id bigint
);

-- changeset Caveri:2

ALTER TABLE student ADD FOREIGN KEY (faculty_id) REFERENCES faculty(id);

-- changeset Caveri:3

ALTER TABLE student ALTER COLUMN faculty_id SET NOT NULL;

-- changeset Caveri:4

ALTER TABLE student ADD CONSTRAINT age_constraint CHECK (age >= 16);






